# Generated by Django 4.2.5 on 2023-09-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_slug_alter_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ean',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.FloatField(null=True),
        ),
    ]
