# Generated by Django 4.2.5 on 2023-09-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produto_descricao_alter_produto_ean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='ean',
            field=models.CharField(max_length=13),
        ),
    ]
